### ISSUE TITLE
Lightning invoice expiration always set to 600 seconds.

### ISSUE THREAD

**Issue by rdbell** [lnbits/satspay#2]
Lightning invoice expiration seems to always to be set to 600 seconds regardless of the `time` value provided.

I believe the `expiry` field needs to be set in the call to [create_invoice](https://github.com/lnbits/satspay/blob/b245dfbe293b4d0e792b448ed660a2acd1fc5103/crud.py#L31)

**Comment by swmtr** [comment]
@callebtc - would anybody be able to look into this? I can confirm that this is the case. Each charge expires after 10 minutes which in most situations makes the extension unusable.

In the admin UI, it says waiting (as it should since the time did not elapse yet), but on the charge itself, it only waits 10 minutes. After that there is an error: Payment does not exist.
404".  
In console: api/v1/charge/balance/kSGwNvvrCm4GNETeQoXAy6:1     Failed to load resource: the server responded with a status of 404 ()

**Comment by swmtr** [comment]
Awesome. Works like a charm. thanks
